language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO=django>=1.4,<1.5
  - DJANGO=django>=1.5,<1.6
  - DJANGO=django>=1.6,<1.7
  - DJANGO=django>=1.7,<1.8
  - DJANGO=django>=1.8,<1.9

matrix:
  exclude:
  - python: "3.4"
    env: DJANGO=django>=1.4,<1.5
  - python: "3.3"
    env: DJANGO=django>=1.4,<1.5
  - python: "3.2"
    env: DJANGO=django>=1.4,<1.5
  - python: "2.6"
    env: DJANGO=django>=1.7,<1.8
  - python: "2.6"
    env: DJANGO=django>=1.8,<1.9

install:
  - pip install $DJANGO coverage==3.6

script:
  - coverage run --source=polymorphic runtests.py
  - coverage report -m

after_success:
  - pip install coveralls==0.2
  - coveralls

branches:
  only:
    - master
